[[truisa-rv32t]]
== RV32T/RV64T的标记指针

在RV32T/RV64T中，线性地址采用标记指针(Tagged Pointer)格式，将内存对象的元数据信息以压缩编码的形式保存在线性地址高TLEN的未使用位域中。
标记指针由两部分组成：标记(Tag)位域和线性地址位域(Address)。
在RV32T中，标记位域是8比特，TLEN=8，线性地址是24比特。在Rv64T中，标记位域是16比特，只用高9比特，其余保留，TLEN=9，线性地址是48比特。

四种类型的标记指针：

描述符表标记指针（S-Radix)：在对象描述符表中存在相对应的描述符表项，采用形心标记的哈希对象表。通过S-Radix和Address有硬件计算形心标记。该类型指针只能由Malloc等库函数生成，不能由用户程序直接生成。描述符表也有库函数和操作系统管理。

描述符寄存器标记指针（RegIndex)：存在相对应的Reg描述符CSR寄存器，RV32T共有8个，RV64T共有16个，通过Reg位域直接索引。只能由Malloc等库函数或者操作系统生成，不能由用户程序直接生成。该类寄存器建议存储一些固定对象，如数据段、代码段、系统段等等。（Future，暂不实现）

固定尺寸标记指针（F-Radix）：F-Radix指定的2的幂次方大小的内存对象。用户程序可以通过标记修改指令生成的标记指针，必须符合权限单调性原则。

固定类型标记指针（PtrType）：基本类型的指针，PtrType指定指针所指数据的类型位宽（2的PtrType个字节）。固定类型标志指针不能进行指针算数运算。用户程序可以通过标记修改指令生成的标记指针，必须符合权限单调性原则。

基本原则：对小数据对象采用F-Radix指针，对基本数据类型采用PtrType类型，对特殊数据段采用RegIndex类型，其他都采用S-Radix类型。

下图阐明了RV32T/RV64T的标记指针格式，表1解释了标记各个字段的含义。

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T标记指针格式*
      |31   |30|29 |28|27|26     |25     |24|23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   7+^|0x00                          19+^|Address
   1+^|0 5+^|S-Radix          1+^|W  19+^|Address 
   1+^|0 2+^|11 3+^|RegIndex  1+^|W  19+^|Address 
   1+^|1 5+^|F-Radix          1+^|W  19+^|Address
   1+^|1 2+^|11 3+^|PtrType   1+^|W  19+^|Address
   7+^|0xFF                          19+^|Address
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T标记指针格式*
      |63   |62|61 |60|58|59|57 |56    |55|...|...|49|48|47|46|45|...|...|7|6|5|4|3|2|1|0
   8+^|0x0000                      18+^|Address
   1+^|0 6+^|S-Radix         1+^|W 18+^|Address 
   1+^|0 2+^|11 4+^|RegIndex 1+^|W 18+^|Address 
   1+^|1 6+^|F-Radix         1+^|W 18+^|Address
   1+^|1 2+^|11 4+^|PtrType  1+^|W 18+^|Address
   8+^|0xFFFF                      18+^|Address
|===

RV32T标记说明：

如果标记位域是0x00或者0xFF，则表示该指针为线性地址，非标记指针。否则，

线性地址最高位如果清0，表示标记位域是描述符表标记指针。线性地址最高位如果置1，表示标记位域是固定尺寸标记指针模式，其中：

W和R表示读写执行权限，00无权限；01可执行可读权限；10只读权限；11可读可写权限。

S-Radix表示Address所在内存对象的Centroid标识是2的S-Radix幂次方大小和对齐内存块的中间点地址。

S-Radix不能等于0，否则是非法标记，产生标记违例。

当S-Radix位域大于等于24时，是描述符寄存器标记指针，RegIndex位域表示8个描述符CSR寄存器的索引号。

F-Radix表示Address所在内存对象是固定大小的内存块，块大小和对齐都是2的F-Radix幂次方。F-Radix必须小于24。
当F-Radix位域大于24时，PtrType表示指针类型数据的位宽（2的PtrType个字节），该类型指针不能进行指针运算操作。

PtrType不能等于7，否则是非法标记，产生标记违例。

NT表示Non-Terminal, 支持Saturation地址生成模式；

RV64T标记指针说明：

如果标记位域是0x0000或者0xFFFF，则表示该指针为线性地址，非标记指针。否则，

S-Radix必须不能等于0，否则是非法标记，产生标记违例。

当S-Radix位域大于等于48时，RegIndex表示16个对象描述符CSR寄存器索引。

F-Radix必须小于48.当F-Radix位域大于48时，PtrType指针类型数据的位宽（字节数），不能进行指针运算操作，

PtrType不能等于15，否则是非法标记，产生标记违例。

下表表示RV32T和RV64T的描述符格式

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T对象描述符格式*
      |31   |30    |29    |28    |27    |26    |25   |24      |23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   1+^|V 1+^|NT 1+^|IN 1+^|FR 1+^|X  1+^|R  1+^|W   19+^|Bound Address 
   1+^|P 5+^|PageSize                       1+^|PL  19+^|Base Address 
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T对象描述符格式*
      |63   |62    |61    |60    |59   |58    |57   |56     |55|54        |53|...|48 |47|46|45|...|...|7|6|5|4|3|2|1|0
   1+^|V 1+^|NT 1+^|IN 1+^|FR 1+^|Na 1+^|X 1+^|R  1+^|W  18+^|Bound Address 
   1+^|P 6+^|PageSize                            1+^|PL 18+^|Base Address 
|===

V: Valid，描述符表项是否有效。

NT: Null-Terminal，是否是‘空’表示结尾的流数据（如字符串）。

IN: Initial，对象是否已经初始化

FR: Freed，对象是否已经被释放。

X、W、R: Execute/Read/Write

PL：特权级，Object Privilege Level (OPL) (Future，默认RV32T为1、RV64T为3，即用户权限)

P: Page/Range，虚实地址转换是采用区间表还是页表，PageSize表示，在页表模式下的页大小，在区间模式下表示mmap()函数生成的区域Centroid表示计算S-Radix，用来索引Range Table。

<<<
== TruISA-RISC-V 指令编码

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |   0|
15+^|*RV32T Base Instruction Set*
 6+^|imm[11:0]                2+^|rs1   2+^|101    2+^|rd           2+^|0001111 <|INCPTRI
 6+^|imm[11:0]                2+^|rs1   2+^|110    2+^|rd           2+^|0001111 <|TAGPTRI
 6+^|imm[11:0]                2+^|rs1   2+^|111    2+^|rd           2+^|0001111 <|LPTR
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|111    2+^|imm[4:0]     2+^|0100011 <|SPTR
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|SUBPTR
 4+^|0000100        2+^|00000 2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|PTRTAG
 4+^|0000101        2+^|00000 2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|PTRINT
 4+^|0000110        2+^|00000 2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|PTRBASE
 4+^|0100110        2+^|00000 2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|PTRBOUND
 4+^|0001100        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|SLTUPTR
 4+^|0010100        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|INCPTR
 4+^|0010100        2+^|00000 2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|MVPTR
 4+^|0110100        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|DECPTR
 4+^|0011000        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|TAGPTR
 4+^|0011001        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|INTPTR
 4+^|0011010        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|SIZEPTR
 4+^|0011011        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0001111 <|ANDPERM
 4+^|0011101        2+^|rs2   2+^|rs1   2+^|011    2+^|00000        2+^|0001111 <|LDOLBD
 4+^|0111101        2+^|rs2   2+^|rs1   2+^|011    2+^|00000        2+^|0001111 <|LDOLBI
 4+^|0011110        2+^|00000 2+^|rs1   2+^|011    2+^|00000        2+^|0001111 <|INVOLBD
 4+^|0111110        2+^|00000 2+^|rs1   2+^|011    2+^|00000        2+^|0001111 <|INVOLBI
|===

<<<
== RV32T/RV64T 例外

标记检查TC：如果标记中，描述符表标记指针的S-Radix全0；固定类型标记指针的PtrType全1；TAGPTR/ANDPERMS违反RW单调性原则。TAGPTR/SIZEPTR/INTPTR指令的目标内存区域超出原内存对象内存区域的单调违例。

越界检查BC：如果在indptr等指针运算指令和ld/st类指令的地址运算超出rs1定义的内存对象边界，则产生边界溢出违例。固定类型指针进行指针算数运算的偏移违例。如果指针计算结果的标记与源指针（rs1）的标记不相同则产生标记完整性违例。

越权检查PC：指令内存操作与指针和描述符权限不符，CPL大于OPL，读写权限设定不符合单调性；对已经释放的对象进行访问；对未初始化的对象进行访问。

|===
|Instruction |TC |BC |PC |违例动作
|INCPTR      |Y  |Y  |N  |标记清0
|DECPTR      |Y  |Y  |N  |标记清0
|INCPTRI     |Y  |Y  |N  |标记清0
|TAGPTR      |Y  |Y  |Y  |标记清0
|TAGPTRI     |Y  |Y  |Y  |标记清0
|INTPTR      |Y  |Y  |N  |标记清0
|SIZEPTR     |Y  |Y  |N  |标记清0
|ANDPERM     |Y  |N  |N  |标记清0
|LPTR        |Y  |Y  |Y  |访存违例处理
|SPTR        |Y  |Y  |Y  |访存违例处理
|LD/ST/AMO   |Y  |Y  |Y  |访存违例处理
|SUBPTR      |N  |N  |N  |无违例
|PTRTAG      |N  |N  |N  |无违例
|PTRINT      |N  |N  |N  |无违例
|PTRBASE     |N  |N  |N  |无违例
|PTRBOUN     |N  |N  |N  |无违例
|SLTUPTR     |N  |N  |N  |无违例
|MVPTR       |N  |N  |N  |无违例
|LDOLBD      |N  |N  |N  |无违例
|LDOLBI      |N  |N  |N  |无违例
|INVOLBD     |N  |N  |N  |无违例
|INVOLBI     |N  |N  |N  |无违例
|===

*访存违例处理：如果SDATE是1则发出例外，否则无任何操作。

<<<
== RV32T/RV64T 指令详解

1. 指针运算指令：

* INCPTR/INCPTRI/DECPTR：进行指针运算，结果位指针类型，并进行标记检查和越界检查。如违例，标记清0。

* SUBPTR/STLUPTR：只对线性地址进行减法和无符号比较操作，结果为整数类型，不进行任何检查。

* MVPTR：简单的复制操作，结果为指针类型，不进行任何检查。。

2. 标记产生指令

* TAGPTR/TAGPTRI：将源操作数的低TLEN位数据复制到目的操作数的高TLEN位中，进行标记检查，越界检查和越权检查，保证单调性。

* INTPTR:将源操作数的线性地址复制到目的操作数的线性地址，进行越界检查，保证单调性。

* SIZEPTR:将源操作数的低radix位域数据复制到目的操作数的radix位域，保持权限位域不变，进行越界检查，保证单调性。

* ANDPERM：将源操作数的低2位和指针的权限位域（W或R)进行按位与操作，F-Radix类型只对W位域进行位与操作。

3. 标记提取指令：

* PTRTAG/PTRBASE/PTRBOUND：将相应位域复制到目标的最低位。

4. 访存指令：

* 进行相应的访存操作，进行所有检查，如果DATE是1则发出例外，否则如果指针内或者描述符中NT是1则越上界访问上界越下界访问下界，否则无任何操作。

5. 对象快表指令：

* LDOLBD/LDOLBI指令，将rs1和rs2作为描述符的高低64位数据，插入OLB中。
* INVOLBD/INVOLBI指令，将rs1中地址所指的OLB表项设为无效，进行标记检查，是否是描述符表标记指针类型S-Radix。

<<<
== RV32T/RV64T CSR详解

3.1.1. Machine ISA Register misa
|===
|Bit       |Character |Description
|19        |T         |RV32/64T base ISA
|===

3.1.15. Machine Cause Register (mcause)
|===
|Interrupt |Exception |priority |Code Description
|0         |32        |as 1     |Instruction tag violation
|0         |33        |as 1     |Instruction permission violation
|0         |34        |as 1     |Instruction bound violation
|0         |35        |as 5     |Load/Store/AMO tag violation
|0         |36        |as 5     |Load permission violation
|0         |37        |as 5     |Load bound violation
|0         |38        |as 5     |Store/AMO permission violation
|0         |39        |as 5     |Store/AMO bound violation
|0         |44        |as 1     |Instruction object fault
|0         |45        |as 5     |Date object fault
//|0         |46        |as 0     |Pointer operation fault
|===

3.1.18. Machine Environment Configuration Register (menvcfg)

|===
|Bit       |Character |Description
|16        |SIATE      |Secure Instruction Trap Enable
|17        |SDATE      |Secure Data Trap Enable
//|18        |SPOTE      |Secure Pointer Operation Trap Enable
|===

待定设计：

8个 Object Descriptor CSR in RV32T (Future)

16个 Ojbect Descriptor CSR in RV64T (Future)
