[[truisa-rv32t]]
== RV32T/RV64T的标记指针

RV32T/RV64T的非特权、特权功能、指令编码等继承Cheriot的定义，但权能指针（Capability）采用Tagged Pointer形式，指针位宽与RISC-V ABI兼容。

Truisa与Cheriot的区别在于：

* 取消指针中关于Permission, Sealed, ObjectType，Flags等等的支持和相关指令，原因是必须采用Fat Pointer，ABI不兼容。

* 取消标记存储（Memory Taging）的设计选择，原因是硬件设计比较复杂或者影响性能。
支持指针完整性，可以采用更先进的编程语言和编译器进行静态形式化检查，或者可以采用加密的方法解决。

* 将Top(对象最后字节地址的后继地址)改为Limit，对象最后字节地址，因为采用标记指针，无法表示最高地址字节的后继字节地址。

* 取消Cheriot中的特殊寄存器设计，因为ABI指针位宽兼容，可以修改和复用原CSR定义。增加BoundViolation和TagViolation两个例外Code即可。

* 支持OMU(Object Management Unit)，包括大于8个条目的对象描述符表缓冲器，（ODBObject Descriptor Buffer），ODB采用软件管理方式，设计专用的指令。

在RV32T/RV64T中，地址采用标记指针(Tagged Pointer)格式，将内存对象的元数据信息以压缩编码的形式保存在线性地址高TLEN的未使用位域中。
标记指针由两部分组成：指针标记(PtrTag)位域和线性地址位域(Address)。
在RV32T中，标记位域是6比特，TLEN=6，线性地址是26比特。在Rv64T中，标记位域是7比特，TLEN=7，线性地址是57比特。

TruISA定义了2种类型的标记指针：

固定尺寸标记指针（F-Radix）：F-Radix指定的2的幂次方大小和对齐的内存对象。用户程序可以通过标记修改指令生成的标记指针，必须符合权限单调性原则。

描述符表标记指针（S-Radix)：在对象描述符表中存在相对应的描述符表项，采用形心标记的哈希对象表。通过S-Radix和Address由硬件计算形心标记。
该类型指针只能由Malloc等库函数生成，不建议用户程序直接定义。描述符表也由库函数或操作系统管理。

基本原则：对小数据对象和规整数据对象采用F-Radix指针类型，对大数据对象和非规整数据对象采用S-Radix类型。

下图阐明了RV32T/RV64T的标记指针格式，表1解释了标记各个字段的含义。

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T标记指针格式 (26比特线性地址）*
      |31      |30|29|28|27|26     |25|24|23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   6+^|0x00                    20+^|Address   
   1+^|0    5+^|S-Radix        20+^|Address    
   1+^|1    5+^|F-Radix        20+^|Address 
   6+^|0x3F                    20+^|Address
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T标记指针格式（57比特线性地址）*
      |63      |62|61 |60|58|59|57     |56|55|...|...|49|48|47|46|45|...|...|7|6|5|4|3|2|1|0
   7+^|0x00                        19+^|Address
   1+^|0    6+^|S-Radix            19+^|Address 
   1+^|1    6+^|F-Radix            19+^|Address
   7+^|0x7F                        19+^|Address
|===

RV32T标记说明：

如果标记位域是0x00或者0x3F，则表示该指针为整数，非标记指针。否则，

指针最高位如果置1，表示标记位域是描述符表标记指针。线性地址最高位如果清0，表示标记位域是固定尺寸标记指针模式，其中：

S-Radix表示Address所在内存对象的Centroid标识是2的S-Radix幂次方大小和对齐的内存块中间点地址。

S-Radix大于0，小于等于26，大于26的值都按照26处理。

F-Radix表示Address所在内存对象是固定大小的内存块，块大小和对齐都是2的F-Radix幂次方。

F-Radix大于0，小于等于26，大于26的值都按26处理。

RV64T标记指针说明：

如果标记位域是0x00或0x7F，则表示该指针为线性地址，非标记指针。否则，

S-Radix大于0，小于等于57，大于57的值都按57处理。

F-Radix大于0，小于等于57，大于57的值都按57处理。

下表表示RV32T和RV64T的描述符格式(草案，第一阶段，只保留Bound, Base，其他权限部分先不实现)

处理器应该包含多余8个条目的ODB，如果标记指针是描述符表格式，则采用Centroid动态的查找ODB，如果查找不到（Miss），则发出例外。

Capability Exception Codes增加0x20，作为ODB失效的例外ODBMissViolation。（Cheriot手册图7.3）

如果发生例外，应该查找malloc中的对象表，重新插入ODB。如果对象被释放（Free），应该插入Limit为0的描述符。

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T对象描述符格式*
      |31   |30   |29 |28 |27    |26|25|24|23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   1+^|R 1+^|W 4+^|Reserved  20+^|Limit Address 
   6+^|Reserved              20+^|Base Address 
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T对象描述符格式*
      |63   |62    |61 |60 |59 |58 |57     |56|55|54|53|...|48 |47|46|45|...|...|7|6|5|4|3|2|1|0
   1+^|R 1+^|W 5+^|Reserved                     19+^|Limit Address 
   7+^|Reserved                     19+^|Base Address 
|===

V: Valid，描述符表项是否有效。
 
== TruISA-RISC-V的指令
去除Cheri-RISC-V中所有关于Perm, Type, Seal, Flags相关的指令。

<<<
== TruISA-RISC-V 指令编码

[%autowidth.stretch,float="center",align="center",cols="<4m, >4m, <2m, >3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31          |   25|24  |  20|19  |  15|14  |   12|11      |      7| 6   |   0|
13+^|*RV32T Base Instruction Set*
 2+^|0001001        2+^|rs2   2+^|cs1   2+^|000    2+^|00000        2+^| 0001111 <|TFENCE.VMA
 2+^|0001010        2+^|00000 2+^|00000 2+^|000    2+^|00000        2+^| 0001111 <|TODBW
 2+^|1111111        2+^|00010 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetBase
 2+^|1111111        2+^|01010 2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CMove
 2+^|1111111        2+^|01111 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetAddr
 2+^|1111111        2+^|11000 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetLimit
 2+^|0000001        2+^|src   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CSpecialRW
 2+^|0000100        2+^|rs2   2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|TSetDescriptor
 2+^|0001000        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CSetBounds
 2+^|0010000        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CSetAddr
 2+^|0010001        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CIncAddr
 2+^|0010100        2+^|cs2   2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CSub
 2+^|0100010        2+^|cs2   2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CSetEqualExact
 4+^|imm[11:0]                2+^|rs1   2+^|100    2+^|cd           2+^| 0001111 <|CIncAddrImm
 4+^|imm[11:0]                2+^|rs1   2+^|101    2+^|cd           2+^| 0001111 <|CSetBoundsImm
 4+^|imm[11:0]                2+^|cs1   2+^|111    2+^|cd           2+^| 0000011 <|CLC
 2+^|imm[11:5]      2+^|cs2   2+^|cs1   2+^|111    2+^|imm[4:0]     2+^| 0100011 <|CSC
|===

<<<
== RV32T/RV64T 例外
 
* 标记检查：如果标记全0或者全1，则不是标记指针，如果是描述符标记指针，查找ODB，如果缺失，则发出例外。

* 越界检查：如果在CIncAddr等指针运算指令和ld/st类指令的地址运算超出cs1定义的内存对象边界，则产生边界溢出违例。
  如果指针计算结果cd的标记与源指针（cs1）的标记不相同则产生标记完整性违例。
  标记设置指令的目标内存区域超出原内存对象内存区域的单调违例。

* 访存指令违例处理，发出例外。

* 标记指针运算和设置指令指令产生违例，目标cd的High符号扩展，产生整数地址，不发例外。

<<<
== RV32T/RV64T 指令详解

1. 指针运算指令：

* CIncAddr/CIncAddrImm：进行指针运算，结果位指针类型，并进行标记检查和越界检查。如违例，符号扩展产生整数地址。

* CSub：只对线性地址进行减法和无符号比较操作，结果为整数类型，不进行任何检查。

* CMove：简单的复制操作，结果为指针类型，不进行任何检查。

2. 边界设置指令

* CSetBounds/CSetBoundImm：将源操作数的低TLEN位数据复制到目的操作数的高TLEN位中，越界检查，保证单调性，如违例线性地址符号扩展，生成整数指针。

3. 边界提取指令：

* 将边界域复制到目标的最低位。

4. 访存指令：

* 进行所有检查，如违例则发出例外。

5. 标记指针访存指令：

* 对地址计算进行所有检查，对于访存数据不做任何检查，如违例则发出例外。

6. 对象描述符缓冲器指令

* TSetDescriptor指令，将cs1作为base，rs2作为limit和读写权限，生成标记指针写入cd，描述如写入默认scr寄存器对（26, 27)中。
进行cs1的标记指针格式检查。
进行单一性检查。(base,limit)不能超出cs1的边界范围，limit中的读写权限不能超出cs1的读写权限（如果有）。

* TODBW指令，将指定的scr寄存器对（26，27）写入ODB中。

* TFENCE.VMA指令，flush ODB，rs2和cs1的功能和SFENCE.VMA类似。