[[truisa-rv32t]]
== RV32T/RV64T的标记指针

RV32T/RV64T的大部分非特权功能、特权功能、指令编码等继承Cheriot的定义，但权能指针（Capability）采用标记指针（Tagged Pointer形式），指针位宽与RISC-V ABI兼容。

Truisa与Cheriot的区别在于：

* 取消权能指针中关于Sealed, ObjectType，Flags等等的支持和相关指令，将Permission缩减到支持可写权限（W, Writeable）。因此，不支持Cheri/cheriot中定义的隔离功能。

* 取消标记存储（Memory Tagging）的设计。保留通用寄存器标记支持。如果需要支持指针完整性，可以采用其他方式，如编程语言和编译器进行静态形式化检查，或者可以采用指针加密等方法解决。

* 将Top(对象最后字节地址的后继地址)改为bound，对象最后字节地址。因为采用标记指针，无法表示最高地址字节的后继字节地址。

* 取消Cheriot中的特殊寄存器设计, 取消PCC和CGP。因为ABI指针位宽兼容，可以修改和复用原CSR定义。

* 增加OMU(Object Management Unit)，包括至少2个条目的描述符旁视缓冲器（DLB, Descriptor Lookaside Buffer），DLB采用软件指令插入方式，DLB应该采用cache类似的结构。

在RV32T/RV64T中，地址采用标记格式，将内存对象的元数据信息以压缩编码的形式保存在线性地址高TLEN的未使用位域中。
标记指针由两部分组成：指针标记(PtrTag)位域和线性地址位域(Address)。
在RV32T中，标记位域是7比特，TLEN = 7，线性地址是25比特（支持32MB寻址）。在Rv64T中，标记位域是8比特，TLEN = 8，线性地址是56比特（支持64TB寻址）。

TruISA定义了2种类型的标记指针：

固定尺寸标记指针（F-Type）：所有对象大小是2的幂次方大小和对齐。用户程序可以通过CSetBound和CSetBoundImm指令设定，需要符合权限单调性原则。

描述符表标记指针（S-Type）：在对象描述符表中存在相对应的描述符表项，采用形心（Centroid）标记的哈希对象表。通过指针标记和线性地址由硬件计算形心标识（ID)。

标记指针类型算则的基本原则是，对小数据对象（设定一定的阈值）和规整数据对象采用F-Type指针类型，对大数据对象和非规整数据对象采用S-Type类型。

下图阐明了RV32T/RV64T的标记指针格式，表1解释了标记各个字段的含义。

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T标记指针格式 (26比特线性地址）*
      |31   |30|29|28|27 |26    |25|24|23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   7+^|0x00                 19+^|Address   
   1+^|0 5+^|S-Radix  1+^|W 19+^|Address    
   1+^|1 5+^|F-Radix  1+^|W 19+^|Address 
   7+^|0x7F                 19+^|Address
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T标记指针格式（57比特线性地址）*
      |63   |62|61|60|58|59|57 |56    |55|...|...|49|48|47|46|45|...|...|7|6|5|4|3|2|1|0
   8+^|0x00                       18+^|Address
   1+^|0 6+^|S-Radix        1+^|W 18+^|Address 
   1+^|1 6+^|F-Radix        1+^|W 18+^|Address
   8+^|0xFF                       18+^|Address
|===

RV32T标记说明：

如果标记位域是0x00或者0x7F，则表示该指针为整数地址，非标记指针。

W表示该标记指针是否有可写（writeable)权限，默认为1，可由CAndPerm指令改变成只写（readonly）权限。

指针最高位如果置0，表示标记位域是S-Type标记指针。其中：

* S-Radix表示Address所在内存对象的Centroid标识是2的S-Radix幂次方大小和对齐的内存块中间点地址。S-Radix大于0，小于等于25，如果大于25的值都按照25处理。

* F-Radix表示Address所在内存对象是固定大小的内存块，块大小和对齐都是2的F-Radix幂次方。F-Radix小于等于25，大于25的值都按25处理。

RV64T标记指针说明：

如果标记位域是0x00或0xFF，则表示该指针为整数地址，非标记指针。否则，

* S-Radix大于0，小于等于56，大于56的值都按56处理。

* F-Radix小于等于56，大于56的值都按56处理。

== 描述符表和描述附表旁视缓冲器

下表表示RV32T和RV64T的描述符格式，包括Bound, Base，两部分，base部分必须是标记指针类型。bound为0表示该条目无效。

处理器应该包含至少2条目的DLB，如果标记指针是描述符表格式，则采用Centroid动态的查找DLB，如果查找不到（Miss），则发出DLB例外。

如果发生例外，应该查找malloc中的对象描述符表，重新插入DLB中。如果对象被释放（Free），应该将DLB和ODT中的表项同时无效。

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV32T描述符旁视缓冲表项格式*
      |31   |30|29|28|27|26 |25    |24|23|22|21|20|19|18|17|...|...|...|7|6|5|4|3|2|1|0
   1+^|0 5+^|S-Radix     1+^|W 19+^|Base Address 
   6+^|Reserved          1+^|W 19+^|Bound Address 
|===

{empty} +
[%autowidth.stretch,float="center",align="center",cols="26*"]
|===
  26+^|*RV64T描述符旁视缓冲表项格式*
      |63   |62|61|60|59|58 |57    |56|55|54|53|...|48 |47|46|45|...|...|7|6|5|4|3|2|1|0
   1+^|0 6+^|S-Radix     1+^|W 18+^|Base Address 
   7+^|Reserved          1+^|W 18+^|Bound Address
|===

CSR寄存器

.Currently allocated RISC-V unprivileged CSR addresses for trusia.
[float="center",align="center",cols="<10%,<10%,<20%,<60%",options="header"]
|===
|Number |Privilege |Name |Description
4+^|Unprivileged Descriptor Lookaside Buffer CSRs

|`0x081` +
`0x082`

|URW +
URW

|`dlbentrybound` +
`dlbentrybase`

|Descriptor Lookaside Buffer Entry Bound. +
Descriptor Lookaside Buffer Entry Base. 

|===

这两个CSR寄存器，也是OLB的一部分，具备边检检查功能。

== TruISA-RISC-V的指令
去除Cheri-RISC-V中所有关于ObjectType, Seal, Flags相关的指令。
去除Capability Special Register的指令。

增加3条描述符表项生成指令和DLB相关指令。

<<<
== TruISA-RISC-V 指令编码

[%autowidth.stretch,float="center",align="center",cols="<4m, >4m, <2m, >3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31          |   25|24  |  20|19  |  15|14  |   12|11      |      7| 6   |   0|
13+^|*RV32T Base Instruction Set*
 2+^|0001001        2+^|00000 2+^|cs1   2+^|000    2+^|00000        2+^| 0001111 <|TFENCE.VMA
 2+^|0001010        2+^|00000 2+^|cs1   2+^|000    2+^|00000        2+^| 0001111 <|TDLBRW
 2+^|1111111        2+^|00000 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetPerm
 2+^|1111111        2+^|00010 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetBase
 2+^|1111111        2+^|01010 2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CMove
 2+^|1111111        2+^|01111 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetAddr
 2+^|1111111        2+^|11000 2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CGetBound
 2+^|0000100        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|TSetDesc
 2+^|0001100        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CAndPerm
 2+^|0001000        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CSetBounds
 2+^|0010000        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CSetAddr
 2+^|0010001        2+^|rs2   2+^|cs1   2+^|011    2+^|cd           2+^| 0001111 <|CIncAddr
 2+^|0010100        2+^|cs2   2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CSub
 2+^|0100010        2+^|cs2   2+^|cs1   2+^|011    2+^|rd           2+^| 0001111 <|CSetEqualExact
 4+^|imm[11:0]                2+^|rs1   2+^|100    2+^|cd           2+^| 0001111 <|CIncAddrImm
 4+^|imm[11:0]                2+^|rs1   2+^|101    2+^|cd           2+^| 0001111 <|CSetBoundsImm
 4+^|imm[11:0]                2+^|cs1   2+^|111    2+^|cd           2+^| 0000011 <|CLC
 2+^|imm[11:5]      2+^|cs2   2+^|cs1   2+^|111    2+^|imm[4:0]     2+^| 0100011 <|CSC
|===

<<<
== RV32T/RV64T 例外
 
* 标记检查：如果标记全0或者全1，则不是标记指针，如果是描述符标记指针，查找DLB，如果缺失，则发出例外。

* 越界检查：如果在CIncAddr等指针运算指令和ld/st类指令的地址运算超出cs1定义的内存对象边界，则产生边界溢出违例。
  如果指针计算结果cd的标记与源指针（cs1）的标记不相同则产生标记完整性违例。
  标记指针设置指令的目标内存区域超出原内存对象内存区域的单调违例。

* 访存指令违例处理，发出例外。

* 标记指针运算和设置指令指令产生违例，目标对cd中的线性地址符号扩展，使指针标记全0或者全1，产生整数地址，不发例外。

<<<
== RV32T/RV64T 指令详解

1. 指针运算指令：

* CIncAddr/CIncAddrImm：进行指针运算，结果是指针类型，并进行标记检查和越界检查。如违例，线性地址符号扩展的整数地址。W位相同。

* CSub：只对线性地址进行减法操作，结果为整数类型，不进行任何检查。

* CMove：简单的复制操作，结果为指针类型，不进行任何检查。

2. 边界设置指令

* CSetBounds/CSetBoundImm，cs1作为base地址，rs2是对象长度，生成大于rs2长度的最小F-Radix作为cd的F-Radix，W位相同。

3. 边界提取指令：

* 将边界域复制到目标寄存器的最低位。

4. 访存指令：

* 进行所有检查，如违例则发出例外。

5. 标记指针访存指令：

* 对地址计算进行标记检查和越界检查，进行权限检查，如违例则发出例外。对于被访问的指针不做任何检查。

6. 对象描述符缓冲器指令

* TSetDesc指令，将cs1作为base，rs2作为bound，生成S-Type标记指针写入cd。base和bound须符合单调性原则是cs1的子集。

* TDLBRW指令，将指定的csr寄存器对（dlbentrybase, dlbentrybound）写入DLB中，cs1作为标记指针必须与dlbentrybase相同。

* TFENCE.VMA指令，执行DLB清楚操作（flush），cs1如果是全0，表示清除所有DLB表项，否则只清楚cs1指示的DLB表项。


== 对象描述符表和描述符旁视缓冲器使用说明

产生DLB描述符缺失例外。根据mtval CSR寄存器中的例外产生地址，软件查找缺失对象描述符

如果需要生成一个新的对象描述符

1. 用CSetAddr生成新的base保存到cs1，将新的bound保存到rs2寄存器中。

2. 使用TSetDesc指令生成S-Type的标记指针, cs1是对象的base，rs2是对象的bound，cd是对象的标记指针。保证生成的内存对象是cs1内存对象的子集。

3. 需要软件更新对象描述符表。

4. base用CLC指令装入，bound用LW/LD装入。

5. 使用CSRRW指令将上述指令的base和bound，分别写入dlbentrybase和dlbentrybound两个CSR寄存器中。

6. 使用TDLBRW指令，cs1是dlbentrybase和dlbentrybound两个CSR所描述的对象的标记指针。检查cs1是否与dlbentrybase相同。

如果对象描述符已经在ODT表中了，则只需要执行4-6部。
